[
  {
    name: "SearchSession",
    value: "41e86a2a%2D3c67%2D43bd%2D95cf%2Db627ad184405",
    domain: "www.winmarkremote.com",
    path: "/",
    expires: -1,
    size: 57,
    httpOnly: false,
    secure: false,
    session: true,
    sameParty: false,
    sourceScheme: "Secure",
    sourcePort: 443,
  },
  {
    name: "ASP.NET_SessionId",
    value: "pue41cgcte0wf04xv1kozc2e",
    domain: "www.winmarkremote.com",
    path: "/",
    expires: -1,
    size: 41,
    httpOnly: true,
    secure: false,
    session: true,
    sameParty: false,
    sourceScheme: "Secure",
    sourcePort: 443,
  },
  {
    name: "FedAuth",
    value:
      "77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+MCMuZnx3aW5tYXJrbWVtYmVyc2hpcHByb3ZpZGVyfHNlYW5tY2xhcmVuLDAjLmZ8d2lubWFya21lbWJlcnNoaXBwcm92aWRlcnxzZWFubWNsYXJlbiwxMzMzNjAzNjA5OTIwNTkxMzMsRmFsc2UsVHM1NFAwRUQ4Y0VaeS9CeDNtVXoyVUV4bEpSOVFaK2RlKzZLR3NtVWM1UnVETDhTNDNleWI4Vm94NWJvS0VXVW5DTHFvbGtySlJvRGhNV2RQVG5kVk9pYS90dHYwN1kwMWFuNUR6RXFHMXhLcUhWVUZBS3k4dDQ2NXJ5VnZDMHdLTWJ3MnhqQTZxajJaa2lqZk5MeDdtVkVnK2YyMzdqdGhUMjJzY2pZc0gyTG1PRlFEQzhYUUxoMlcwRFhvUzhEMU13UkRURVpvRTBmenYvc3BZR1RlamdFWUE2MTRVWllzam5nZmxtSEtKTStIanhITXRhdFp2L0F0QXFnMHlDS3ZBLzgybGhveEMyYUhvTDNoeFViV2lCZlEwdHMrQ0t4aWFCSUljay9tMDBFYVBBQTBqMUJhWExvTjJDc1pudlU0Uy82NlFJcnJkZE1SbGZnLzkxVW9BPT0saHR0cHM6Ly93d3cud2lubWFya3JlbW90ZS5jb20vPC9TUD4=",
    domain: "www.winmarkremote.com",
    path: "/",
    expires: -1,
    size: 723,
    httpOnly: true,
    secure: true,
    session: true,
    sameParty: false,
    sourceScheme: "Secure",
    sourcePort: 443,
  },
  {
    name: "WSS_FullScreenMode",
    value: "false",
    domain: "www.winmarkremote.com",
    path: "/",
    expires: -1,
    size: 23,
    httpOnly: false,
    secure: false,
    session: true,
    sameParty: false,
    sourceScheme: "Secure",
    sourcePort: 443,
  },
  {
    name: "/reports/Reserved.ReportViewerWebPart.axd%3FOpType%3DSessionKeepAlive%26ControlID%3D26c1ead5e6b44afeb3d6200ea10b48b1_SKA",
    value: "1",
    domain: "www.winmarkremote.com",
    path: "/reports/_layouts/15/ReportServer",
    expires: -1,
    size: 121,
    httpOnly: false,
    secure: false,
    session: true,
    sameParty: false,
    sourceScheme: "Secure",
    sourcePort: 443,
  },
];
